import type {
  PluginCatalogEntry,
  PluginId,
  PluginTier,
} from "./pluginTypes";

type PluginCatalog = Record<PluginId, PluginCatalogEntry>;

export const PLUGIN_CATALOG: PluginCatalog = {
  "velvet-curve": {
    id: "velvet-curve",
    name: "Velvet Curve",
    description: "Dynamic tone shaper inside the Velvet Doctrine.",
    tier: "pillar",
    tierLabel: "Five Pillars",
    parameters: ["attack", "release", "tilt", "mix"],
    moodResponse: "Breathes with transient density; smooths harsh edges when ALS hears fatigue.",
    lightingProfile: { hueStart: 210, hueEnd: 260, motion: "breathe" },
    curated: true,
  },
  "harmonic-lattice": {
    id: "harmonic-lattice",
    name: "Harmonic Lattice",
    description: "Upper harmonic excitation & spatial glide.",
    tier: "pillar",
    tierLabel: "Five Pillars",
    parameters: ["density", "focus", "spread", "mix"],
    moodResponse: "Expands shimmer as harmonic tension rises.",
    lightingProfile: { hueStart: 300, hueEnd: 340, motion: "shimmer" },
  },
  "mixx-fx": {
    id: "mixx-fx",
    name: "Mixx FX",
    description: "Quick modulation stack tuned for Flow gestures.",
    tier: "pillar",
    tierLabel: "Five Pillars",
    parameters: ["texture", "warp", "deg", "mix"],
    moodResponse: "Highlights fills and drops; pulses with ALS tempo energy.",
    lightingProfile: { hueStart: 260, hueEnd: 320, motion: "pulse" },
  },
  "time-warp": {
    id: "time-warp",
    name: "Time Warp",
    description: "Context-aware micro timing and warp engine.",
    tier: "pillar",
    tierLabel: "Five Pillars",
    parameters: ["stretch", "bend", "quantize", "slew"],
    moodResponse: "Locks on groove drift, aligning performers to Studio feel.",
    lightingProfile: { hueStart: 180, hueEnd: 220, motion: "sweep" },
  },
  "mixx-tune": {
    id: "mixx-tune",
    name: "Mixx Tune",
    description: "AI vocal tuner and tone-former.",
    tier: "core",
    tierLabel: "Core Tier",
    parameters: ["retuneSpeed", "formant", "humanize", "mix", "emotiveLock"],
    moodResponse: "Follows lyric sentiment and section changes; adjusts mood confidence.",
    lightingProfile: { hueStart: 210, hueEnd: 330, motion: "float" },
    curated: true,
  },
  "mixx-verb": {
    id: "mixx-verb",
    name: "Mixx Verb",
    description: "Adaptive reverb space engine.",
    tier: "core",
    tierLabel: "Core Tier",
    parameters: ["size", "predelay", "mix"],
    moodResponse: "Reacts to energy level; widens with intensity.",
    lightingProfile: { hueStart: 180, hueEnd: 270, motion: "breathe" },
  },
  "mixx-delay": {
    id: "mixx-delay",
    name: "Mixx Delay",
    description: "Intelligent throw delay.",
    tier: "core",
    tierLabel: "Core Tier",
    parameters: ["time", "feedback", "mix", "throwIntuition"],
    moodResponse: "Syncs to pulse; throws bloom during chorus lifts.",
    lightingProfile: { hueStart: 300, hueEnd: 300, motion: "pulse" },
  },
  "mixx-drive": {
    id: "mixx-drive",
    name: "Mixx Drive",
    description: "Harmonic saturator and color enhancer.",
    tier: "core",
    tierLabel: "Core Tier",
    parameters: ["drive", "warmth", "mix", "color"],
    moodResponse: "Boosts saturation as ALS hears RMS rise.",
    lightingProfile: { hueStart: 300, hueEnd: 30, motion: "burst" },
  },
  "mixx-glue": {
    id: "mixx-glue",
    name: "Mixx Glue",
    description: "Bus compressor tuned for cohesion.",
    tier: "core",
    tierLabel: "Core Tier",
    parameters: ["threshold", "ratio", "release", "mix"],
    moodResponse: "Smooths transitions, eases build-ups.",
    lightingProfile: { hueStart: 270, hueEnd: 270, motion: "pulse" },
    canBeSidechainTarget: true,
  },
  "mixx-limiter": {
    id: "mixx-limiter",
    name: "Mixx Limiter",
    description: "Ceiling control inside the master lane.",
    tier: "master",
    tierLabel: "Master Tier",
    parameters: ["ceiling", "drive", "lookahead", "clubCheck"],
    moodResponse: "Tightens headroom and matches club translation.",
    lightingProfile: { hueStart: 0, hueEnd: 0, motion: "pulse" },
    canBeSidechainTarget: true,
    curated: true,
  },
  "mixx-clip": {
    id: "mixx-clip",
    name: "Mixx Clip",
    description: "Soft clipper for transient harnessing.",
    tier: "master",
    tierLabel: "Master Tier",
    parameters: ["ceiling", "drive", "softness", "mix"],
    moodResponse: "Guards the crown while preserving sparkle.",
    lightingProfile: { hueStart: 10, hueEnd: 35, motion: "burst" },
  },
  "mixx-aura": {
    id: "mixx-aura",
    name: "Mixx Aura",
    description: "Psychoacoustic width enhancer.",
    tier: "neural",
    tierLabel: "Neural Tier",
    parameters: ["tone", "width", "shine", "moodLock"],
    moodResponse: "Mirrors room mood; widens with energy.",
    lightingProfile: { hueStart: 330, hueEnd: 270, motion: "float" },
  },
  "prime-eq": {
    id: "prime-eq",
    name: "Prime EQ",
    description: "Adaptive EQ guided by Prime Brain context.",
    tier: "neural",
    tierLabel: "Neural Tier",
    parameters: ["lowGain", "midGain", "highGain", "smartFocus"],
    moodResponse: "Balances frequency bands dynamically; smooth color drift.",
    lightingProfile: { hueStart: 180, hueEnd: 270, motion: "pulse" },
  },
  "mixx-polish": {
    id: "mixx-polish",
    name: "Mixx Polish",
    description: "Spectral enhancer for sheen.",
    tier: "neural",
    tierLabel: "Neural Tier",
    parameters: ["clarity", "air", "balance"],
    moodResponse: "Adds top-end sparkle when energy peaks.",
    lightingProfile: { hueStart: 50, hueEnd: 50, motion: "shimmer" },
  },
  "mixx-morph": {
    id: "mixx-morph",
    name: "Mixx Morph",
    description: "Transitional FX for sectional movement.",
    tier: "neural",
    tierLabel: "Neural Tier",
    parameters: ["transitionTime", "morphDepth", "syncMode"],
    moodResponse: "Bridges sections; syncs lighting to arrangement cues.",
    lightingProfile: { hueStart: 0, hueEnd: 360, motion: "sweep" },
  },
  "prime-brain-stem": {
    id: "prime-brain-stem",
    name: "Prime Brain Stem",
    description: "Neural conductor collecting cue packets.",
    tier: "neural",
    tierLabel: "Neural Tier",
    parameters: [],
    moodResponse: "Ships mood frames to ALS and Bloom petals.",
    lightingProfile: { hueStart: 0, hueEnd: 0, motion: "pulse" },
    curated: true,
  },
  "mixx-balance": {
    id: "mixx-balance",
    name: "Mixx Balance",
    description: "Stereo and phase alignment coach.",
    tier: "master",
    tierLabel: "Master Tier",
    parameters: ["width", "phase", "tilt"],
    moodResponse: "Adjusts spatial balance automatically.",
    lightingProfile: { hueStart: 210, hueEnd: 210, motion: "drift" },
  },
  "mixx-ceiling": {
    id: "mixx-ceiling",
    name: "Mixx Ceiling",
    description: "Final energy regulator.",
    tier: "master",
    tierLabel: "Master Tier",
    parameters: ["level", "softClip", "tone"],
    moodResponse: "Smooths peaks; shapes brightness for recall.",
    lightingProfile: { hueStart: 0, hueEnd: 0, motion: "expand" },
  },
  "prime-master-eq": {
    id: "prime-master-eq",
    name: "Prime Master EQ",
    description: "High-precision master equalizer.",
    tier: "master",
    tierLabel: "Master Tier",
    parameters: [
      "lowShelfFreq",
      "lowShelfGain",
      "highShelfFreq",
      "highShelfGain",
      "midSideMode",
    ],
    moodResponse: "Shapes final tone subtly to respect translation notes.",
    lightingProfile: { hueStart: 40, hueEnd: 60, motion: "sweep" },
  },
  "mixx-dither": {
    id: "mixx-dither",
    name: "Mixx Dither",
    description: "Noise shaping and bit-depth finesse.",
    tier: "master",
    tierLabel: "Master Tier",
    parameters: ["bitDepth", "noiseShaping", "ditherAmount"],
    moodResponse: "Applies final bit-depth conversion when exports arm.",
    lightingProfile: { hueStart: 200, hueEnd: 220, motion: "shimmer" },
  },
  "mixx-soul": {
    id: "mixx-soul",
    name: "Mixx Soul",
    description: "Emotion-to-harmonic mapper.",
    tier: "signature",
    tierLabel: "Signature Halo",
    parameters: ["empathy", "depth", "tone", "vibe"],
    moodResponse: "Colors midrange based on lyrical emotion and chat resonance.",
    lightingProfile: { hueStart: 210, hueEnd: 50, motion: "shimmer" },
  },
  "mixx-motion": {
    id: "mixx-motion",
    name: "Mixx Motion",
    description: "Rhythmic LFO movement engine.",
    tier: "signature",
    tierLabel: "Signature Halo",
    parameters: ["rate", "depth", "sync"],
    moodResponse: "Animates panning and movement against groove shifts.",
    lightingProfile: { hueStart: 300, hueEnd: 300, motion: "pulse" },
  },
  "prime-lens": {
    id: "prime-lens",
    name: "Prime Lens",
    description: "Audio-to-visual translator for Studio overlays.",
    tier: "signature",
    tierLabel: "Signature Halo",
    parameters: ["gain", "resolution", "colorMode"],
    moodResponse: "Feeds visuals to MAE layers when scenes change.",
    lightingProfile: { hueStart: 0, hueEnd: 360, motion: "sweep" },
  },
  "mixx-brainwave": {
    id: "mixx-brainwave",
    name: "Mixx Brainwave",
    description: "Generative idea composer.",
    tier: "signature",
    tierLabel: "Signature Halo",
    parameters: ["seed", "variation", "intensity"],
    moodResponse: "Suggests melodic ideas when creative energy dips.",
    lightingProfile: { hueStart: 270, hueEnd: 270, motion: "flare" },
  },
  "mixx-spirit": {
    id: "mixx-spirit",
    name: "Mixx Spirit",
    description: "Live crowd sentiment engine.",
    tier: "signature",
    tierLabel: "Signature Halo",
    parameters: ["sensitivity", "energyLink", "threshold"],
    moodResponse: "Adjusts brightness via fan sentiment loops.",
    lightingProfile: { hueStart: 0, hueEnd: 360, motion: "pulse" },
  },
  "mixx-analyzer-pro": {
    id: "mixx-analyzer-pro",
    name: "Mixx Analyzer Pro",
    description: "Visual LUFS and spectrum monitor.",
    tier: "system",
    tierLabel: "System Layer",
    parameters: [],
    moodResponse: "Displays energy and frequency without numeric clutter.",
    lightingProfile: { hueStart: 210, hueEnd: 300, motion: "bars" },
    curated: true,
  },
  "prime-router": {
    id: "prime-router",
    name: "Prime Router",
    description: "Signal patch matrix and mod orbit.",
    tier: "system",
    tierLabel: "System Layer",
    parameters: [],
    moodResponse: "Manages routing and modulation links contextually.",
    lightingProfile: { hueStart: 0, hueEnd: 0, motion: "glow" },
  },
  "mixx-port": {
    id: "mixx-port",
    name: "Mixx Port",
    description: "Export engine for Mixx format.",
    tier: "system",
    tierLabel: "System Layer",
    parameters: ["format", "quality"],
    moodResponse: "Fires completion glow when renders finish.",
    lightingProfile: { hueStart: 270, hueEnd: 270, motion: "pulse" },
  },
  "telemetry-collector": {
    id: "telemetry-collector",
    name: "Telemetry Collector",
    description: "Studio system logger.",
    tier: "system",
    tierLabel: "System Layer",
    parameters: [],
    moodResponse: "Records every gesture and mood frame for Mixx Recall.",
    lightingProfile: { hueStart: 0, hueEnd: 0, motion: "heartbeat" },
  },
  "prime-bot-console": {
    id: "prime-bot-console",
    name: "PrimeBot Console",
    description: "Chat and AI assistant surface.",
    tier: "system",
    tierLabel: "System Layer",
    parameters: [],
    moodResponse: "Displays PrimeBot hints and mood commentary.",
    lightingProfile: { hueStart: 0, hueEnd: 360, motion: "mirror" },
  },
};

export const TIER_ORDER: Record<PluginTier, number> = {
  pillar: 0,
  core: 1,
  neural: 2,
  master: 3,
  system: 4,
  signature: 5,
};

