
// components/AIHub/ImageGenerator.tsx
import React, { useState, useCallback, useRef } from 'react';
import { GoogleGenAI } from "@google/genai";
import { getGeminiAI } from '../../utils/gemini';
import LoadingSpinner from '../common/LoadingSpinner';
import RadioButton from '../common/RadioButton';
import { ImageIcon } from '../icons';

type ImageAspectRatio = "1:1" | "3:4" | "4:3" | "9:16" | "16:9";

const ImageGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [aspectRatio, setAspectRatio] = useState<ImageAspectRatio>("1:1");
  const [generatedImageUrl, setGeneratedImageUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const ai = useRef(getGeminiAI());

  const generateImage = useCallback(async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim()) {
      setError("Please enter a prompt for image generation.");
      return;
    }

    setIsLoading(true);
    setError(null);
    setGeneratedImageUrl(null);

    try {
      const response = await ai.current.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
          aspectRatio: aspectRatio,
        },
      });

      const base64ImageBytes = response.generatedImages?.[0]?.image?.imageBytes;
      if (base64ImageBytes) {
        setGeneratedImageUrl(`data:image/jpeg;base64,${base64ImageBytes}`);
      } else {
        setError("No image was generated. Please try a different prompt.");
      }
    } catch (err: any) {
      console.error("Error generating image:", err);
      setError(`Failed to generate image: ${err.message || 'Unknown error'}`);
    } finally {
      setIsLoading(false);
    }
  }, [prompt, aspectRatio]);

  return (
    <div className="flex flex-col h-full bg-gray-900/60 rounded-lg p-4 shadow-inner">
      <form onSubmit={generateImage} className="flex-shrink-0 mb-4 space-y-4">
        <div>
          <label htmlFor="prompt" className="block text-sm font-medium text-gray-300 mb-1">
            Image Prompt:
          </label>
          <textarea
            id="prompt"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="A robot holding a red skateboard in a futuristic city at sunset."
            rows={3}
            className="w-full p-3 rounded-lg bg-gray-800 text-gray-100 border border-gray-700 focus:outline-none focus:ring-2 focus:ring-fuchsia-500"
            disabled={isLoading}
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-300 mb-2">
            Aspect Ratio:
          </label>
          <div className="flex flex-wrap gap-4">
            {["1:1", "3:4", "4:3", "9:16", "16:9"].map((ratio) => (
              <RadioButton
                key={ratio}
                label={ratio}
                value={ratio}
                checked={aspectRatio === ratio}
                onChange={(val) => setAspectRatio(val as ImageAspectRatio)}
                name="aspectRatio"
                color="fuchsia"
              />
            ))}
          </div>
        </div>

        <button
          type="submit"
          className="w-full px-6 py-3 bg-fuchsia-600 text-white rounded-lg font-semibold hover:bg-fuchsia-500 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          disabled={isLoading || !prompt.trim()}
        >
          Generate Image
        </button>
      </form>

      <div className="flex-grow flex items-center justify-center bg-gray-800/50 rounded-lg overflow-hidden relative">
        {isLoading && <LoadingSpinner message="Generating your image..." color="fuchsia" />}
        {error && (
          <div className="text-red-400 text-center p-4">{error}</div>
        )}
        {generatedImageUrl ? (
          <img
            src={generatedImageUrl}
            alt="Generated by AI"
            className="max-w-full max-h-full object-contain rounded-lg shadow-lg"
          />
        ) : !isLoading && !error && (
          <div className="flex flex-col items-center text-gray-500">
            <ImageIcon className="w-16 h-16 text-gray-600 mb-4" />
            <p className="text-lg">Your generated image will appear here.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default ImageGenerator;